version: '3'

networks:
  datapipeline:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"

services:
  spark:
    image: docker.io/bitnami/spark:3
    container_name: spark_master
    hostname: spark_master
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    volumes:
      - bitnami-data:/opt/bitnami
      - ./project-data:/home
    networks:
      datapipeline:
        ipv4_address: 172.18.0.2

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      datapipeline:
        ipv4_address: 172.18.0.3

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://172.18.0.4:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.18.0.4:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    volumes:
      - ./project-data:/home
    networks:
      datapipeline:
        ipv4_address: 172.18.0.4
  jupyter:
    build:
      context: .
      dockerfile: ./jupyter/Dockerfile
    volumes:
      - ./work:/home/jovyan/work
      - bitnami-data:/bitnami
      - ./log-cron:/cron-log

    environment:
      - FLASK_APP='/home/jovyan/work/comment-youtube/self/app.py'
      - FLASK_DEBUG=true
    ports:
      - '8503:8501'
      - 8888:8888
      - '8945:8945'
    container_name: jupyter_notebook
#    command: "start-notebook.sh --NotebookApp.token="
    working_dir: "/home/jovyan/work/comment-youtube/self"
#    command: "cron -f"
    networks:
      datapipeline:
        ipv4_address: 172.18.0.6

  mysql:
    image: 'mysql:5.7.16'
    container_name:   mysql
    hostname:   mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=cons
      - MYSQL_PASSWORD=pass
    volumes:
      - ./datadir:/var/lib/mysql
    networks:
      datapipeline:
        ipv4_address: 172.18.0.9
volumes:
  bitnami-data: